---
title: "01.Clean F0 Data"
output: html_document
date: "2023-05-21"
---

```{r setup, include=FALSE}
library(readr) #read_csv()
library(dplyr)
library(stringr)
library(ggplot2)
library(tidyr)

data.clean <- function(dataframe){
  dataframe <- dataframe %>%
    mutate(
    dia = str_extract(filename,"diaN?[1-2]?n?"),
    condition = str_split_i(filename, "diaN?[1-2]?n?",-1),
    focus = str_sub(filename,-1,-1),
    tone = str_sub(condition,1,str_length(condition)-1),
    participant = str_extract(filename, "S[0-9]+"),
    char_duration = maxTime - minTime,
    tone = as.factor(tone),
    focus = as.factor(focus),
    participant = as.factor(participant),
    uniqueID = paste0(as.character(filename),"_",as.character(enum)),
    case = as.factor(case),
  )
}
data.f0 <- function(dataframe){
  dataframe <- dataframe %>%
    filter(case != "ADD") %>%
    filter(case != "Aspect")
}
```

## Read data
```{r basic clean}
cantonese.raw <- read_tsv("../extract_acoustics_results/230526Cantonese_data.tsv", col_names = TRUE,show_col_types = FALSE)
cantonese.clean <- data.clean(cantonese.raw)

cantonese_realf0.raw <- read_tsv("../extract_acoustics_results/230526Cantonese_realf0_data.tsv", col_names = TRUE,show_col_types = FALSE)
cantonese_realf0.clean <- data.clean(cantonese_realf0.raw)

# Add a new variable for the last word in the sentence
## Note: changsha condition 3 needs modification! the last sentence is not part of the word
# cantonese.clean <- cantonese.clean %>%
#   group_by(filename) %>%
#   mutate(
#     boundary = if_else(idx == max(idx, na.rm = TRUE),1,0)
#   ) %>%
#   ungroup()
```
## Data for f0 check
1. ignore idx = 0, but keep SFP
2. ignore the functional particles
```{r}
cantonese.target <- data.f0(cantonese.clean)
cantonese.realf0.target <- data.f0(cantonese_realf0.clean)
```

## Check f0 missing data

The listed files need to be manually checked in the folder.

Make sure there is no files left here.
```{r}
missingnormf0 <- cantonese.target[rowSums(is.na(as.matrix(cantonese.target[,startsWith(names(cantonese.target), "t")])))>0, ]
# cantonese.realf0.target[is.nan(cantonese.realf0.target$f0),]
```

## Transform f0 data and calculate f0 in semitones
```{r transformation}
cantonese.long <- cantonese.target %>%
  pivot_longer(cols = matches('t[0-9]+', ignore.case = FALSE), names_to = "Time",names_prefix = "t", values_to = "f0") %>% # Convert to the standard long format
  group_by(participant) %>%
  mutate(
    f0ref = mean(f0, na.rm = T),
    f0_semi = 12*log(f0/f0ref,2)
  ) %>%
  ungroup()

cantonese_realf0.long <- cantonese.realf0.target  %>%
    group_by(participant) %>%
  mutate(
    f0ref = mean(f0, na.rm = T),
    f0_semi = 12*log(f0/f0ref,2),
    Time = time * 1000
  ) %>%
  ungroup()
  
```

## Save the files to use the algorhithm later

```{r}
write.csv(cantonese.long, "./datafiles/Cantonese_forf0check.csv", row.names = FALSE)
write.csv(cantonese_realf0.long, "./datafiles/Cantonese_realf0_forf0check.csv", row.names = FALSE)
write.csv(missingnormf0, "./datafiles/Cantonese_missingf0_check.csv", row.names = FALSE)
```

